language: python

matrix:
    include:
      python: 3.6
      dist: xenial
      sudo: true

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install: 
  - pip install -r ./requirements.txt

os: 
  - osx
